// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Name struct {
	First    string `json:"first"`
	Middle   string `json:"middle"`
	Last     string `json:"last"`
	Username string `json:"username"`
}
