// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Blog struct {
	Link          string `json:"link"`
	DateOfRelease string `json:"dateOfRelease"`
}

type Name struct {
	First    string `json:"first"`
	Middle   string `json:"middle"`
	Last     string `json:"last"`
	Username string `json:"username"`
}

type Skill struct {
	Name             string `json:"name"`
	Description      string `json:"description"`
	CreatedAt        string `json:"createdAt"`
	SkillsCategoryID string `json:"skillsCategoryID"`
	UpdatedAt        string `json:"updatedAt"`
}

type SkillInput struct {
	Name             string `json:"name"`
	Description      string `json:"description"`
	SkillsCategoryID string `json:"skillsCategoryID"`
}

type SkillsCategory struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type SkillsCategoryInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Social struct {
	Name    string `json:"name"`
	Profile string `json:"profile"`
}
